# Generated by Django 4.1.1 on 2022-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_user_available_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.IntegerField()),
                ("day", models.IntegerField()),
                ("price", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("arc_year", models.IntegerField()),
                ("gu", models.IntegerField()),
                ("dong", models.IntegerField()),
                ("pyeong", models.IntegerField()),
                ("cont_year", models.IntegerField()),
                ("cont_mon", models.IntegerField()),
                ("river", models.IntegerField()),
                ("age", models.IntegerField()),
                ("rebuild", models.IntegerField()),
                ("apt_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Asset",),
    ]
